version: '2'

services:
  app:
    restart: always
    build:
      context: ./app/
      args:
      - SVN_USERNAME
      - SVN_PASSWORD
    expose:
      - '8000'
      - '8888'
    ports:
      - '8000:8000'
      - '8888:8888'
    volumes:
      - static:/usr/src/app/static
    command: python3 manage.py gunicorn
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - '80:80'
    links:
      - app:app

volumes:
  static:
